# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: "etl_weather_db"
    image: postgres
    restart: "no"
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - testWeather:/var/lib/postgresql/data
  
  adminer:
    container_name: "etl_weather_adminer"
    image: adminer
    restart: "no"
    ports:
      - 8080:8080
volumes:
  testWeather: