# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: "etl_weather_db"
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: openweather
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - testWeather:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql # database seeder

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - testPGAdmin:/var/lib/pgadmin

volumes:
  testWeather:
  testPGAdmin: